In [ ]:
import os
import urllib
import requests
from bs4 import BeautifulSoup
from collections import defaultdict
import pandas as pd
from datetime import datetime

In [ ]:
!pip3 install pdfminer.six 
!pip install PyPDF2
!pip install pdfplumber
import pdfminer.high_level
from pdfminer.high_level import extract_text

import PyPDF2,pdfplumber 
 

CV_File=open('/content/Hari Prasad Resume 1.pdf','rb')
Script=PyPDF2.PdfFileReader(CV_File)
pages=Script.numPages

Script = []
with pdfplumber.open(CV_File) as pdf:
    for i in range (0,pages):
        page=pdf.pages[i]
        text=page.extract_text()
        # print (text)
        Script.append(text)
        
Script=''.join(Script)
CV_Clear = Script.replace("\n","").replace('●', "")
CV_Clear

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pdfminer.six in /usr/local/lib/python3.8/dist-packages (20221105)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.8/dist-packages (from pdfminer.six) (38.0.4)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from pdfminer.six) (2.1.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=36.0.0->pdfminer.six) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six) (2.21)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.8/dist-packages (2.12.1)
Requirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.8/dist-packages (from PyPDF2) (4.4.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.8/dist-packages (0.7.6)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.8/dist-packages (from pdfplumber) (9.3.0)
Requirement already satisfied: Wand>=0.6.10 in /usr/local/lib/python3.8/dist-packages (from pdfplumber) (0.6.10)
Requirement already satisfied: pdfminer.six==20221105 in /usr/local/lib/python3.8/dist-packages (from pdfplumber) (20221105)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.8/dist-packages (from pdfminer.six==20221105->pdfplumber) (38.0.4)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from pdfminer.six==20221105->pdfplumber) (2.1.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20221105->pdfplumber) (2.21)

'HARI PRASAD RENGANATHAN106 W 105th st, Apt 18, New York, NY 917-238-4627linkedin.com/in/hariprasad20/ hr2514@columbia.eduEDUCATIONColumbia University New York, NYMaster of Science, Data Science Dec 2022Coursework: Machine Learning for Data Science, Exploratory Data Analytics and Visualization, Algorithms for DataScience, AI Applications in Finance, Finance and Structuring for Data ScienceKumaraguru College of Technology Coimbatore, IndiaBachelor of Engineering, Mechanical Engineering Jun2021Awarded with meritorious scholarship ($600) 3 times for excelling in top 5% of the departmentSKILLS Tools:Python, R, MS Excel, Tableau, SQL, WordPress,Snowflake, AWS Libraries/Frameworks:Pandas, Numpy, Matplotlib, Seaborn,Scikit-learn, Keras, Beautiful Soup, ggplot2, Git, Dash Data techniques:Neural Networks (Deep learning),Supervised and Unsupervised Machine Learning, ExploratoryData Analysis, Web Scraping, Data Visualization, Hypothesis Testing, Time Series, ETL, StatisticsEXPERIENCETake-two Interactive Software, Inc. New York, NYData Scientist May 2022 - Present Contributed to 4 major Enterprise Data Science/ Analytics projects in the Sales team Collaborated with ML Engineers and Data analysts to deploy price elasticity outputs from AWS S3 buckets intoproduction as an interactive dashboard using Dash Optimized sales-forecasting model by introducing ARIMA and improved performance by 33% Mined and analyzed data of 72 different companies to perform competitive analysis using hypothesis testingleveraging Snowflake, SQL and Tableau Performed market research of company’s 12 subsidiaries and presented the patterns to Marketing departmentAsk2AI New York, NYFinancial Data Scientist Spring Intern Jan 2022 -May 2022 Forecasted future returns and volatility using 650-dimensional macro-economic time-Series data Applied rolling window Principal Component Analysis (PCA); built a predictive model using LSTM Neural NetworksGoTTR New York, NYFounding member & Data Scientist Jul 2021 - Dec 2021 Regularized Data-Scraping & Data-Modeling for 100 GB which reduced manual work of 4 hours to few seconds Led a team of 5 to computerize the Data Management on Google Cloud (GCP) and established an Email-Alert systemwhich saved $7000 a month (Tools used: Python, SQL, Pandas, Scikit-learn)DADDYODA Coimbatore, IndiaCo-founder & Marketing Data Scientist Jul 2020 - Jul2021 Automated 50+ weekly promotional emails to 10k+ users using Python increased efficiency by 30%; performedmarketing analytics using Tableau which increased the user count by 50% Predicted the sentiments of customer reviews using text analytics which reduced Customer Acquisition Cost by 20%PROJECTSTime Series Forecasting and Analysis of Onion Supply Chain (Research Study) Jan 2022Published in the “Journal of Logistics, Supply Chain and Retail Management – Volume 5 Issue 1” Collaborated with 3 members and implemented Exploratory Data Analytics (EDA), predictive analytics and forecastedonion prices for 2 years using Autoregressive Integrated Moving Average (ARIMA) model Performed macro-economic analysis and ETL pipeline using Tableau to optimize the supply chain modelRanking US stocks using machine learning based on financial ratios (Columbia University) Dec 2021 Gathered live financial analysis ratios of S&P 500 stocks using Beautiful Soup and SQL for database management Trained a Random Forest Model using Hyper-parameter tuning (GridSearchCV) to rank US stocksRental Price Analysis for New York City (Columbia University) Nov 2021 Analyzed rental market in New York City and performed Hypothesis testing using R programming Designed a Web-interface and rendered using Github workflow -https://karveandhan.github.io/rental-price/Stock Price Prediction using EV/EBITDA valuation model (Columbia University) May 2021 Collected financial data and performed data mining and visualization techniques using BI tools like Tableau Predicted future 12 months price of Index stocks using statistical analysis of Enterprise Value & EBITDA model'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# search inputs: 
title = input('Enter your desired position: ').strip()
location = input('Enter your desired location: ').strip()
no_pages = int(input('Enter the # of pages to scrape: '))


info = []
headers = {'User-agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'}

for page in range(no_pages):
    getVars = {'keywords' : title, 'location' : location ,'sort' : 'date', 'start': str(no_pages*10)}
    url = ('https://www.linkedin.com/jobs/search?' + urllib.parse.urlencode(getVars))
    print(url)
    r = requests.get(url, headers=headers)
    html = r.content
    soup = BeautifulSoup(html, "html.parser")
    
    jobs = soup.find_all('div', class_ = 'base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card')
    
    for job in jobs:
        title = str(job.find('h3', class_='base-search-card__title').text.strip())
        company = str(job.find('h4', class_='base-search-card__subtitle').text.strip())
        post_date = datetime.strptime(job.find('time')['datetime'], '%Y-%m-%d').date()
        link = job.find('a', class_='base-card__full-link')['href']
        
        info.append([title,company,post_date,link])
    

info_dict_list = defaultdict(list)

cols = ['Job_title','Company','Job_posted_date','Link']
info_table = pd.DataFrame(info, columns = cols)
# sort by post date
info_table = info_table.sort_values(by = 'Job_posted_date', ascending = False).reset_index(drop=True)
info_table

Enter your desired position: Data Scientist
Enter your desired location: United States
Enter the # of pages to scrape: 50
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Junior+Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Data+Scientist&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Machine+Learning+Engineer&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Machine+Learning+Engineer+-+Cupertino&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Machine+Learning+Software+Engineer-Photos+Algorithms&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Lead+Model-Based+Systems+Engineer+%28MBSE%29&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500
https://www.linkedin.com/jobs/search?keywords=Entry+Level+Model+Based+Systems+Engineer%2FAnalyst&location=United+States&sort=date&start=500

,Job_title,Company,Job_posted_date,Link
0,Machine Learning Engineer,Apple,2022-12-16,https://www.linkedin.com/jobs/view/machine-lea...
1,Data Scientist,SES Corporation,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...
2,Data Scientist,SES Corporation,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...
3,Data Scientist,Maxonic,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...
4,Data Scientist,Idea Financial,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...
...,...,...,...,...
658,Model Based Systems Engineer- Early Career,Lockheed Martin,2022-11-02,https://www.linkedin.com/jobs/view/model-based...
659,Model Based Systems Engineer- Early Career,Lockheed Martin,2022-11-02,https://www.linkedin.com/jobs/view/model-based...
660,Model Based System Engineer-Senior Level,SOLVARUS,2022-10-24,https://www.linkedin.com/jobs/view/model-based...
661,Machine Learning / AI Internship,Apple,2022-10-17,https://www.linkedin.com/jobs/view/machine-lea...
662,Sr. Model-Based Systems Engineer - 100% Remote...,Strategic Technology Consulting - STC,2022-09-22,https://www.linkedin.com/jobs/view/sr-model-ba...

In [ ]:
match_percent = []
for l in info_table['Link']: 
    
    # extract job description from 2nd webpage (ie, main page for each job post)
    r = requests.get(l, headers=headers)
    soup = BeautifulSoup(r.content, "html.parser")
    job_description = soup.find('div', class_='show-more-less-html__markup show-more-less-html__markup--clamp-after-5').text.replace("\n","")
    
    # calculate match percentage 
    Match_Test = [CV_Clear,job_description]
    cv = CountVectorizer()
    count_matrix = cv.fit_transform(Match_Test)
    MatchPercentage = cosine_similarity(count_matrix)[0][1]*100
    match_percent.append(MatchPercentage)
    
match_percent

AttributeError: ignored

In [ ]:
match_percent = pd.DataFrame(match_percent, columns = ['Matching_percentage'])
final_info_table = pd.concat([info_table, match_percent], axis=1)
final_info_table = final_info_table.sort_values(by = 'Matching_percentage', axis = 0, ascending=False)

In [ ]:
# export tp csv file: 
final_info_table.to_csv('final_info_table1.csv', index=False)
final_info_table

,Job_title,Company,Job_posted_date,Link,Matching_percentage
44,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
64,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
22,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
14,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
72,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
...,...,...,...,...,...
658,Model Based Systems Engineer- Early Career,Lockheed Martin,2022-11-02,https://www.linkedin.com/jobs/view/model-based...,NaN
659,Model Based Systems Engineer- Early Career,Lockheed Martin,2022-11-02,https://www.linkedin.com/jobs/view/model-based...,NaN
660,Model Based System Engineer-Senior Level,SOLVARUS,2022-10-24,https://www.linkedin.com/jobs/view/model-based...,NaN
661,Machine Learning / AI Internship,Apple,2022-10-17,https://www.linkedin.com/jobs/view/machine-lea...,NaN
662,Sr. Model-Based Systems Engineer - 100% Remote...,Strategic Technology Consulting - STC,2022-09-22,https://www.linkedin.com/jobs/view/sr-model-ba...,NaN

In [ ]:
print('Here are the top 10 recommended jobs based on your resume:')
final_info_table.nlargest(10,['Matching_percentage'])

Here are the top 10 recommended jobs based on your resume:

,Job_title,Company,Job_posted_date,Link,Matching_percentage
44,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
64,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
22,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
14,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
72,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
10,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
19,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
71,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
32,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154
57,Data Scientist (REMOTE),Foot Locker,2022-12-16,https://www.linkedin.com/jobs/view/data-scient...,64.639154